---
title: "Assignment #9: Part I"
author: "Anna Ehrhorn"
date: "April 11, 2020"
version: "1.0"
output: html_notebook
---

*This notebook is applying knowledge of the Grammar of Graphics Lecture.*


# Part I

***
### Question 1

The creation of the graph to compare the PTSD scores of women who suffered
childhood sexual abuse to those who did not suffer childhood secual abuse.

```{r include=FALSE}
library(here)
library(tidyverse)

abuse.data <- read_csv(here("Data", "Sexual Abuse Data.csv"))

# Checking Data
abuse.data

abuse.data$csa
```

```{r}
ggplot(data = abuse.data) + 
  geom_boxplot(mapping = aes(x = csa, y = ptsd)) +
  labs(x = "Reported Childhood Sexual Abuse", y = "Post-traumatic Stress Disorder (PTSD) Scale 
       (standardized scale)",
       title = "The PTSD scores of Women",
       subtitle = "who did and did not Experience Childhood Sexual Abuse",
       caption = "Higher scores indicate higher PTSD severity") +
  scale_x_discrete(labels = c('Abused','Not Abused'))
```


***
### Question 2
```{r}
ggplot(data = abuse.data) + 
  geom_boxplot(mapping = aes(x = csa, y = ptsd)) +
  labs(x = "Reported Childhood Sexual Abuse", y = "Childhood Physical Abuse Scale 
       (standardized scale)",
       title = "The Childhood Physical Abuse scores of Women",
       subtitle = "who did and did not Experience Childhood Sexual Abuse",
       caption = "Higher scores indicate more Abuse") +
  scale_x_discrete(labels = c('Abused','Not Abused'))
```


***
### Question 3